name:                EntelectChallenge2018
version:             0.1.0.0
github:              "quiescent/EntelectChallenge2018"
license:             GPL-3
author:              "Edward John Steere"
maintainer:          "edward.steere@gmail.com"
copyright:           "2018 Edward John Steere"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quiescent/EntelectChallenge2018#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.2.4.0
- containers >= 0.5.10.0
- vector >= 0.12.0.1
- random >= 1.1
- bytestring >= 0.10.8.2

library:
  source-dirs: src

executables:
  EntelectChallenge2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EntelectChallenge2018

tests:
  EntelectChallenge2018-test:
    main:                Spec.hs
    source-dirs:         test
    buildable: false
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EntelectChallenge2018
